App Gestão: Tela de Tecnologia Padrão
2020-1-DTool/dTool pull request #10
Opened 2020-05-23 01:28 UTC by zfelipesilveira

# App Gestão: Tela de Tecnologia Padrão:

Implementar interface seguindo mockup em anexo

Autores: Felipe

## Checklist

- 🤷‍♀️ funciona em Android
- ✅(opcional) funciona em iOS
- 🤷‍♀️ interface funciona nos tamanhos de tela suportados (testar em AVD Tablet/Celular)
- ✅interface segue especificação no Figma
- ✅passa nos testes funcionais definidos para a tarefa/story
- 🤷‍♀️ documentação atualizada
- ✅ código dentro dos padrões
- ✅ código sem warnings ou erros de linter (rode `npm run lint -- --fix` para ajustar e faça o commit)
- 🤷‍♀️ adiciona dependências externas (✅/⚠️/❌/🤷‍♀️ aprovadas pelos AGES III)

Legenda:

- ✅: sim (funciona/builda/documentação atualizada/...)
- ⚠️: parcialmente (partes não funcionam/apenas documentação pendente/...)
- ❌: não (não builda/não funciona/não segue padrões/sem documentação/...)
- 🤷‍♀️: não se aplica (não tenho como testar no iOS/não envolve interface/...)

## Adicione um screenshot/gif da aplicação após último commit, que seja possível visualizar a alteração

Opcional, mas recomendado.
<img width="445" alt="Captura de Tela 2020-05-22 às 22 29 30" src="https://user-images.githubusercontent.com/49548547/82718839-7cfbab00-9c7b-11ea-93d0-d3bf4062c820.png">

## Outras informações

Comentários extras...

2020-05-23 16:01 UTC, rafaelruwer requested changes

2020-05-23 16:01 UTC, rafaelruwer commented on src/App.tsx
> +          })}
`navigation` não está sendo usado (warning no linter):

```suggestion
          options={{
            title: "Exemplos",
            ...baseHeaderStyle,
          }}
```

2020-05-23 16:01 UTC, rafaelruwer commented on src/screens/admin/DocList.tsx
> +  storageResult: Array<Record<string, any>>;
Para quê serve essa props? Ela não está sendo usada, e acho que não será necessária quando o backend para essa tela estiver pronto.

2020-05-24 01:14 UTC, ghost submitted a review, later dismissed
Com os últimos ajustes e integrações com develop, a branch está pronta para merge

2020-05-24 01:50 UTC, biancacamargomachado approved these changes

2020-05-24 01:50 UTC, merged