Botao soma carousel
2020-1-DTool/dTool pull request #2
Opened 2020-05-20 02:26 UTC by Camilaborba

# Botão de Soma no Carousel

Alterar botão de Soma no Carousel de atividades para retirar da linha, deve-se prototipar a possível solução antes de implementar (enviar para o @viniciusbranco4 para validação com o cliente). Implementar alteração na UI. Implementar funcionalidade do botão de soma, se não tiver tecnologia salva ir para a tela de tecnologia, se tiver tecnologia salva mas não tiver função salva ir para a tela de função, se tiver função vai para a tela de paciente.

**Autores:** Camila e Gabriel 

## Checklist

- ✅/⚠️/❌/🤷‍♀️ funciona em Android ✅
- ✅/⚠️/❌/🤷‍♀️ (opcional) funciona em iOS - não testado 
- ✅/⚠️/❌/🤷‍♀️ interface funciona nos tamanhos de tela suportados (testar em AVD Tablet/Celular) - Testado somente em celular 
- ✅/⚠️/❌/🤷‍♀️ interface segue especificação no Figma ✅
- ✅/⚠️/❌/🤷‍♀️ passa nos testes funcionais definidos para a tarefa/story
- ✅/⚠️/❌/🤷‍♀️ documentação atualizada
- ✅/⚠️/❌/🤷‍♀️ código dentro dos padrões
- ✅/⚠️/❌/🤷‍♀️ código sem warnings ou erros de linter (rode `npm run lint -- --fix` para ajustar e faça o commit) ✅
- ✅/⚠️/❌/🤷‍♀️ adiciona dependências externas (✅/⚠️/❌/🤷‍♀️ aprovadas pelos AGES III)

Legenda:

- ✅: sim (funciona/builda/documentação atualizada/...)
- ⚠️: parcialmente (partes não funcionam/apenas documentação pendente/...)
- ❌: não (não builda/não funciona/não segue padrões/sem documentação/...)
- 🤷‍♀️: não se aplica (não tenho como testar no iOS/não envolve interface/...)

## Adicione um screenshot/gif da aplicação após último commit, que seja possível visualizar a alteração

![botao](https://user-images.githubusercontent.com/19845594/82397972-0adf5800-9a28-11ea-8466-e5d3ffffb192.PNG)

## Outras informações

Comentários extras...

2020-05-20 03:49 UTC, biancacamargomachado commented
Oi, acho que faz parte da tarefa tirar o botão de '+' antigo assim como foi feito no protótipo... ou vão subir isso em outro PR?

2020-05-20 03:54 UTC, biancacamargomachado requested changes

2020-05-20 03:54 UTC, biancacamargomachado commented on src/screens/CarouselScreen.tsx
> +            return navigation.navigate("EmptyScreen");
Clicando nesse botão eu tive esse erro: 
![image](https://user-images.githubusercontent.com/40609384/82403054-51d34a80-9a34-11ea-8c38-7b1c1d94a399.png), não tenho certeza do que era pra ser este "Teste" e se ainda está sendo usado.

2020-05-20 04:02 UTC, Camilaborba commented
Oi, sim faz, acabou que passou despercebido por nós esse detalhe.
Sobre o botão de teste, não esta sendo mais usando, foi só no primeiro
momento que usamos para testar a funcionalidade do botão enquanto não
tínhamos o protótipo do figma aprovado, vou tirar ele.

Em qua., 20 de mai. de 2020 às 00:54, biancacamargomachado <
notifications@github.com> escreveu:

> *@biancacamargomachado* requested changes on this pull request.
> ------------------------------
>
> In src/screens/CarouselScreen.tsx
> <https://github.com/2020-1-DTool/dTool/pull/2#discussion_r427726622>:
>
> >    return (
>
>      <SafeAreaView>
>
>        <View style={styles.body}>
>
>          <Carousel />
>
> +        <ButtonPrimary
>
> +          title="Teste"
>
> +          onPress={() => {
>
> +            return navigation.navigate("EmptyScreen");
>
>
> Clicando nesse botão eu tive esse erro:
> [image: image]
> <https://user-images.githubusercontent.com/40609384/82403054-51d34a80-9a34-11ea-8c38-7b1c1d94a399.png>,
> não tenho certeza do que era pra ser este "Teste" e se ainda está sendo
> usado.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/2020-1-DTool/dTool/pull/2#pullrequestreview-414974339>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEXNDWRQCEXZ6BBDXWNKI7LRSNH6TANCNFSM4NFQXIGA>
> .
>

2020-05-20 14:38 UTC, IgorBrehm commented
oi Camila, teria como adicionar a funcionalidade de, ao selecionar um item na tela de lista de atividades, ir para a tela onde estão os elementos a serem testados?

2020-05-20 18:07 UTC, Camilaborba commented
Oi, foi adicionado.

Em qua., 20 de mai. de 2020 às 11:38, IgorBrehm <notifications@github.com>
escreveu:

> oi Camila, teria como adicionar a funcionalidade de, ao selecionar um item
> na tela de lista de atividades, ir para a tela onde estão os elementos a
> serem testados?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/2020-1-DTool/dTool/pull/2#issuecomment-631515620>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEXNDWRRZYM7CSZDHJSJHJ3RSPTPHANCNFSM4NFQXIGA>
> .
>

2020-05-20 18:33 UTC, IgorBrehm commented
Notei algumas coisas:
1. A verificação de tecnologia e função salvas parece estar funcionando, mas o card não está sendo criado no Carousel após o fim do fluxo. 
2. O fluxo de criação de novo card no Carousel tem um erro/problema: após selecionar a tecnologia estou chegando na tela de início, e deveria ter ido direto pra seleção de função (este é o caso de uso sem ter nada salvo).

2020-05-20 19:04 UTC, Camilaborba commented
Sobre o item 1, a principio não era para ser feito nessa atividade, tem um
card para fazer essa parte (Abrir descrição de atividade ao clicar em um
card do Carousel e ao clicar e um item na lista de atividades adicionar no
carousel), pelo menos eu entendi dessa forma.
Sobre o item 2 está resolvido.


Em qua., 20 de mai. de 2020 às 15:33, IgorBrehm <notifications@github.com>
escreveu:

> Notei algumas coisas:
>
>    1. A verificação de tecnologia e função salvas parece estar
>    funcionando, mas o card não está sendo criado no Carousel após o fim do
>    fluxo.
>    2. O fluxo de criação de novo card no Carousel tem um erro/problema:
>    após selecionar a tecnologia estou chegando na tela de início, e deveria
>    ter ido direto pra seleção de função (este é o caso de uso sem ter nada
>    salvo).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/2020-1-DTool/dTool/pull/2#issuecomment-631649587>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEXNDWU3ZFCBVCEMUFYAK63RSQO73ANCNFSM4NFQXIGA>
> .
>

2020-05-20 19:31 UTC, IgorBrehm commented
Jóia Camila, sendo assim de minha parte agora está tudo ok

2020-05-20 19:34 UTC, IgorBrehm commented
Estava olhando o código alterado no último commit:
1. Com esta alteração, ao selecionar uma tecnologia da lista eu não vou acabar sempre indo pra tela de escolha de função? Existem casos onde ainda queremos para na tela de Início, este pulo para a tela de função deveria ser condicionado ao contexto do fluxo de adição de nova execução através do botão plus, sendo assim algo excepcional e não a norma

2020-05-20 21:27 UTC, rafaelruwer requested changes

2020-05-20 21:27 UTC, rafaelruwer commented on src/App.tsx
> +  const { role } = await localStorage.getPreferences();
Você pode economizar uma leitura do AsyncStorage:

```suggestion
  const { technology, role } = await localStorage.getPreferences();
```

2020-05-20 21:27 UTC, rafaelruwer commented on src/screens/ChooseTechnology.tsx
> +    navigation.reset({ index: 0, routes: [{ name: "ChooseRole" }] });
Isso tem de ser condicional, porque quando o app abre, se não há uma tecnologia selecionada, essa tela deve ser exibida e depois a `Home`, como era.

Como dá pra fazer: quando for pra `ChooseTecnology` a parte da tela de execução, passar um parâmetro (via `navigation`/`params`) que indica que a seleção de tecnologia é pra uma atividade, e verifica esse parâmetro aqui nessa função.

2020-05-20 21:27 UTC, rafaelruwer commented on src/screens/ChooseActivity.tsx
> +    if (activ) navigation.navigate("CarouselScreen");
Acho que aqui devemos usar um `navigation.reset(...)`, pra evitar deixar o usuário voltar pra essa tela quando já estiver na tela de execução:

```suggestion
    if (activ) navigation.reset({ index: 0, routes: [{ name: "CarouselScreen" }] });
```

2020-05-20 21:27 UTC, rafaelruwer commented on src/screens/ChooseTechnology.tsx
> +    navigation.reset({ index: 0, routes: [{ name: "ChooseRole" }] });
Tem mais coisa nisso, agora não sei se não faz parte da integração de tudo; talvez valha a pena só adicionar esse parâmetro nessa task (pra que essa task não fique muito grande, eu acho) e depois, na integração, fazer o resto para começar a executar uma atividade.

2020-05-21 02:00 UTC, Camilaborba commented on src/screens/ChooseActivity.tsx
> +    if (activ) navigation.navigate("CarouselScreen");
Mudança feita.

2020-05-21 02:00 UTC, Camilaborba commented on src/App.tsx
> +  const { role } = await localStorage.getPreferences();
Mudança feita.

2020-05-22 01:28 UTC, biancacamargomachado requested changes

2020-05-22 01:28 UTC, biancacamargomachado commented on src/screens/ChooseActivity.tsx
>      const activ = activities[index];
```suggestion
    const activity = activities[index];
```

2020-05-22 01:28 UTC, biancacamargomachado commented on src/screens/ChooseActivity.tsx
> +    if (activ) {
```suggestion
    if (activity) {
```

2020-05-22 01:28 UTC, biancacamargomachado commented on src/screens/ChooseTechnology.tsx
> +    const { teste } = route.params;
Não entendi o pq de `teste`... considere outro nome pra const pra ajudar entender o contexto desse código aqui.

2020-05-22 01:28 UTC, biancacamargomachado commented on src/screens/EmptyScreen.tsx
> +  const adicionaAtividade = async () => {
só pra manter o padrão de nomenclatura

```suggestion
  const addActivity = async () => {
```

2020-05-22 01:28 UTC, biancacamargomachado commented on src/screens/EmptyScreen.tsx
> +        <ButtonPlus onPress={adicionaAtividade} />
```suggestion
        <ButtonPlus onPress={addActivity} />
```

2020-05-22 01:28 UTC, biancacamargomachado commented on src/screens/EmptyScreen.tsx
>  import { Dimensions, SafeAreaView, StyleSheet, View, Text } from "react-native";
Esse arquivo está sendo usado em algum lugar? senão acho que podemos remover já, era mais pra ajudar no início....

2020-05-22 01:54 UTC, Camilaborba commented
Feito os ajustes apontados pela Bianca e feita o condicional de rota na tela de Tecnologia.

2020-05-22 02:18 UTC, biancacamargomachado submitted a review, later dismissed

2020-05-22 03:11 UTC, rafaelruwer submitted a review, later dismissed

2020-05-22 03:11 UTC, rafaelruwer commented on src/screens/ChooseTechnology.tsx
> +      navigation.reset({ index: 0, routes: [{ name: "ChooseRole" }] });
Aqui, eu acho que não é o caso de resetar a stack de navegação (i.e. usar `navigation.reset`), porque o usuário vai ser direcionado pra tela de seleção de função.
Como é uma mudança mínima, vou aprovar o PR, mas isso deve ser atualizado na integração.

2020-05-22 20:46 UTC, IgorBrehm commented on src/screens/ChooseTechnology.tsx
> +      navigation.reset({ index: 0, routes: [{ name: "ChooseRole" }] });
Alteração realizada

2020-05-22 20:49 UTC, merged