Atualiza contagens em andamento no evento de `focus`
2020-1-DTool/dTool pull request #24
Opened 2020-06-08 01:24 UTC by biancacamargomachado

# [02] Atualizações de contagem de tempo de acordo com o AppState

Este PR é para essa parte:
- Quando fechar o app ou minimizar salvar os tempos de execução para mostrar o tempo atualizado quando retornar ao app

OBS.: [SERÃO FEITOS EM OUTRO(s) PR)]:

- Atualizar os tempos na tela com base no tempo salvo antes de minimizar e no timestamp que retornou ao app [Edu, Jéssica e Bianca]
- Atualizar os cronômetros visuais

**Autores:** Bianca, Felipe e Jéssica

## Checklist

- ✅ funciona em Android
- ⚠️ (opcional) funciona em iOS - comentários no código
- ✅interface funciona nos tamanhos de tela suportados (testar em AVD Tablet/Celular)
- ✅ interface segue especificação no Figma
- 🤷‍♀️ passa nos testes funcionais definidos para a tarefa/story
- ✅ documentação atualizada
- ✅ código dentro dos padrões
- ✅ código sem warnings ou erros de linter (rode `npm run lint -- --fix` para ajustar e faça o commit)
- 🤷‍♀️ adiciona dependências externas (🤷‍♀️ aprovadas pelos AGES III)

Legenda:

- ✅: sim (funciona/builda/documentação atualizada/...)
- ⚠️: parcialmente (partes não funcionam/apenas documentação pendente/...)
- ❌: não (não builda/não funciona/não segue padrões/sem documentação/...)
- 🤷‍♀️: não se aplica (não tenho como testar no iOS/não envolve interface/...)

## Adicione um screenshot/gif da aplicação após último commit, que seja possível visualizar a alteração

**Testar na tela EmptyScreen: iniciar execuções, sair do app e voltar**

Opcional, mas recomendado.
![image](https://user-images.githubusercontent.com/40609384/83984841-5f7e4080-a90d-11ea-8cab-a746917daf37.png)

2020-06-08 20:41 UTC, ghost submitted a review, later dismissed
Testei aqui e parece estar funcionando bem

2020-06-08 23:09 UTC, rafaelruwer requested changes

2020-06-08 23:09 UTC, rafaelruwer commented on src/screens/CarouselScreen.tsx
> +    if (Platform.OS === "android") {
Não dá pra usar o evento `change` e verificar pelo parâmetro o estado do app `active`/`background`?

2020-06-08 23:40 UTC, biancacamargomachado commented on src/screens/CarouselScreen.tsx
> +    if (Platform.OS === "android") {
Dá sim!!

Bem notado, valeu!!

2020-06-08 23:43 UTC, biancacamargomachado commented on src/screens/CarouselScreen.tsx
> +    if (Platform.OS === "android") {
ajustado

2020-06-10 20:29 UTC, ghost approved these changes

2020-06-10 22:44 UTC, merged