Ajuste - Adiciona endDate a execucao finalizada e enviada para backend
2020-1-DTool/dTool pull request #34
Opened 2020-06-26 21:29 UTC by MFischmann

# Horário de finalização da contagem de tempo

Quando o usuário clicar em salvar e enviar contagem de tempo, deve ser coletado data e hora da finalização, da mesma forma que fazemos ao iniciar.

**Autores:** Micael Fischmann

## Checklist

- ✅ funciona em Android
- 🤷‍♀️ (opcional) funciona em iOS
- 🤷‍♀️ interface funciona nos tamanhos de tela suportados (testar em AVD Tablet/Celular)
- 🤷‍♀️ interface segue especificação no Figma
- ✅ passa nos testes funcionais definidos para a tarefa/story
- 🤷‍♀️ documentação atualizada
- ✅ código dentro dos padrões
- ✅ código sem warnings ou erros de linter (rode `npm run lint -- --fix` para ajustar e faça o commit)
- 🤷‍♀️ adiciona dependências externas (✅/⚠️/❌/🤷‍♀️ aprovadas pelos AGES III)

Legenda:

- ✅: sim (funciona/builda/documentação atualizada/...)
- ⚠️: parcialmente (partes não funcionam/apenas documentação pendente/...)
- ❌: não (não builda/não funciona/não segue padrões/sem documentação/...)
- 🤷‍♀️: não se aplica (não tenho como testar no iOS/não envolve interface/...)

## Outras informações

Data e hora da finalização adicionada à estrutura que é enviada para Backend. Modificações no Backend incluindo no banco de dados são necessárias para completar a tarefa.

2020-06-26 21:51 UTC, ghost submitted a review, later dismissed

2020-06-29 15:47 UTC, rafaelruwer requested changes

2020-06-29 15:47 UTC, rafaelruwer commented on src/services/timerFunction.ts
> +      endDate: moment().format("YYYY-MM-DDTHH:mm:ssZZ"),
Acho que tem que tirar esse `ZZ` e deixar só um `Z`, se não me engano isso tinha dado problema em outros lugares do app

2020-06-29 20:38 UTC, MFischmann commented on src/services/timerFunction.ts
> +      endDate: moment().format("YYYY-MM-DDTHH:mm:ssZZ"),
Na linha 67 ainda é utilizado com dois Z. Modifico ambos, só este, ou mantém assim?

2020-06-29 20:42 UTC, IgorBrehm commented on src/services/timerFunction.ts
> +      endDate: moment().format("YYYY-MM-DDTHH:mm:ssZZ"),
Acredito que antes era [Z]ZZ

2020-06-29 20:45 UTC, rafaelruwer approved these changes

2020-06-29 21:04 UTC, biancacamargomachado approved these changes

2020-06-29 21:05 UTC, merged