Timer function
2020-1-DTool/dTool pull request #9
Opened 2020-05-23 00:14 UTC by MFischmann

# Criar função para contagem de tempo

(descrição do card no Trello)

**Autores:** Micael Fischmann micael.fischmann@edu.pucrs.br
**Autores:** Igor Brehm igor.brehm@edu.pucrs.br

## Checklist

- ✅ funciona em Android
- 🤷‍♀️ (opcional) funciona em iOS
- 🤷‍♀️ interface funciona nos tamanhos de tela suportados (testar em AVD Tablet/Celular)
- 🤷‍♀️ interface segue especificação no Figma
- ✅ passa nos testes funcionais definidos para a tarefa/story
- ✅ documentação atualizada
- ✅ código dentro dos padrões
- ⚠️ código sem warnings ou erros de linter (rode `npm run lint -- --fix` para ajustar e faça o commit)
- ✅ adiciona dependências externas (✅/⚠️/❌/🤷‍♀️ aprovadas pelos AGES III)

Legenda:

- ✅: sim (funciona/builda/documentação atualizada/...)
- ⚠️: parcialmente (partes não funcionam/apenas documentação pendente/...)
- ❌: não (não builda/não funciona/não segue padrões/sem documentação/...)
- 🤷‍♀️: não se aplica (não tenho como testar no iOS/não envolve interface/...)

## Outras informações

Possivelmente deve ser alterado no relógio do emulador o fuso horário para horário de Brasília para o horário em ISO8601 ser corretamente apresentado.

Campo de texto em EmptyScreen está somente para fins de teste e só aceita números.

É adicionada uma dependência nova.

2020-05-23 19:06 UTC, biancacamargomachado requested changes

2020-05-23 19:06 UTC, biancacamargomachado commented on src/screens/EmptyScreen.tsx
> +  const cardInfo = {
Só pra gente controlar melhor depois os próximos passos

```suggestion
// TODO: na tela apropriada, pegar dados do paciente atual do AsyncStorage
  const cardInfo = {
```

2020-05-23 19:06 UTC, biancacamargomachado commented on src/services/timerFunction.ts
> +export const createExecution = async (cardInfo: any) => {
Cria um tipo (em `types`) pra especificar os dados que são necessários neste cardInfo, acho que vai facilitar pra depois

```suggestion
export const createExecution = async (cardInfo: CardExecutionType ) => {
```

2020-05-23 19:06 UTC, biancacamargomachado commented on src/services/timerFunction.ts
> +  );
Quando a execução é criada, ela não inicia automático, é necessário selecionar "INICIAR" pra ter um `startTime`. Então eu acho que nesse momento ele deve estar só zerado, certo?

```suggestion
  console.log(
    "timerFunction.createExecution: Criando execução"
  );
```

2020-05-23 19:06 UTC, biancacamargomachado commented on src/services/timerFunction.ts
> +  let newExecution: OngoingExecution = {
```suggestion
  const newExecution: OngoingExecution = {
```

2020-05-23 19:06 UTC, biancacamargomachado commented on src/services/timerFunction.ts
> +/** Função responsável por iniciar contagem de tempo de uma execução
```suggestion
/** Função responsável por iniciar contagem de tempo de uma execução de atividade
```

2020-05-23 19:06 UTC, biancacamargomachado commented on src/services/timerFunction.ts
> +/** Função responsável por criar uma nova execução */
```suggestion
/** Função responsável por criar uma nova execução de atividade
 * @param cardInfo, com os dados para execução atual
 */
```

2020-05-23 19:06 UTC, biancacamargomachado commented on src/services/timerFunction.ts
> +  // Usar get do storage por indice
Pelo que entendi recebe o index, certo?

```suggestion
 * para fazer update de todas as execuções.
 * @param index, índice do objeto no array de execuções de atividade
 */

export const initializeExecution = async (index: number) => {
```

2020-05-23 19:06 UTC, biancacamargomachado commented on src/services/timerFunction.ts
> +  let lstExecution = await getOngoingExecutions();
```suggestion
  const lstExecution = await getOngoingExecutions();
```

2020-05-23 19:06 UTC, biancacamargomachado commented on src/services/timerFunction.ts
> +    let execution: OngoingExecution = JSON.parse(lstExecution)[id];
```suggestion
    const execution: OngoingExecution = JSON.parse(lstExecution)[id];
```

Considere verificar se há outras variáveis que nunca são alteradas no seu contexto, se tiver mais, elas devem ser `const` ao invés de `let`;

2020-05-23 19:06 UTC, biancacamargomachado commented on src/screens/EmptyScreen.tsx
> +            initializeExecution(position);
E nas outras que esperam um número

```suggestion
            initializeExecution(Number(position));
```

2020-05-23 19:06 UTC, biancacamargomachado commented on src/services/timerFunction.ts
> +/** Função responsável por pausar uma execução */
```suggestion
/** 
* Função responsável por pausar uma execução e no momento, o elapsedTime é calculado ao pausar
* @param index, índice da execução a ser pausada no array
 */
```

Considere trocar de `id` pra `index` onde é esperado o índice do array, acho que fica mais fácil de entender o que está sendo feito.

2020-05-23 19:06 UTC, biancacamargomachado commented on src/services/timerFunction.ts
> +export const cancelExecution = async (id: number) => {
Tentei usar o cancelar e não funcionou aqui, conseguem dar uma conferida se está ok ou n?

![image](https://user-images.githubusercontent.com/40609384/82738610-2cce2880-9d0f-11ea-9a8f-49f1c997f812.png)

2020-05-23 21:26 UTC, IgorBrehm commented on src/services/timerFunction.ts
> +  );
Eu estava analisando o código e não me pareceu ser um problema, então vou manter como está

2020-05-23 21:32 UTC, IgorBrehm commented on src/services/timerFunction.ts
> +  );
o método initializeExecution garante a integridade do startTime e outras variáveis do objeto

2020-05-23 21:36 UTC, MFischmann commented on src/services/timerFunction.ts
> +export const cancelExecution = async (id: number) => {
Oi, Bianca, tu teria o log do terminal também?

2020-05-23 21:39 UTC, IgorBrehm commented on src/services/timerFunction.ts
> +export const cancelExecution = async (id: number) => {
vou verificar esse item por último

2020-05-23 22:01 UTC, rafaelruwer requested changes

2020-05-23 22:01 UTC, rafaelruwer commented on package.json
> +    "moment": "^2.26.0",
Se uma dependência externa é adicionada, o `package-lock.json` também tem de ser atualizado.

2020-05-23 22:01 UTC, rafaelruwer commented on src/services/types.ts
> +  currentState: ExecutionStatus;
Uma execução finalizada não estará sempre no estado `Finished`? Esse atributo sempre terá o mesmo valor, não?

2020-05-23 22:01 UTC, rafaelruwer commented on src/services/asyncStorageAdapter.ts
> +  return true;
As implementações dessas duas funções são exatamente iguais, acho que vale a pena criar uma função "genérica" (cujo parâmetro `newItem` seja `any`, por exemplo) e fazer essas duas apenas invocarem a nova função.

2020-05-23 22:01 UTC, rafaelruwer commented on src/services/asyncStorageAdapter.ts
> +  console.log(`✅ ${key}: ${currentList}`);
Acho que não precisa logar o valor que acabou de ser salvo no Async Storage (é uma leitura desnecessária).

2020-05-23 22:01 UTC, rafaelruwer commented on src/services/localStorage.ts
> +export const getFinishedExecutions = () => getItem("@finishedExecution");
Essa função deveria retornar um array, não? Acho mais fácil usar a `getArray(...)`.

2020-05-23 22:01 UTC, rafaelruwer commented on src/services/localStorage.ts
> +export const getOngoingExecutions = () => getItem("@ongoingExecution");
Mesma coisa: acho que isso deveria retornar um array, então dá pra usar `getArray` (que não precisa usar `JSON.parse` sempre depois de chamar essa função).

2020-05-23 22:01 UTC, rafaelruwer commented on src/services/timerFunction.ts
> +    latestStartTime: startTime,
Na mesma linha do comentário da @biancacamargomachado: uma execução é criada como `Uninitialized`, o timestamp do início dela é do instante que o usuário toca no botão _"Iniciar"_, então `startTime` e `latestStartTime` devem ser `null` aqui.

2020-05-23 22:01 UTC, rafaelruwer commented on src/services/asyncStorageAdapter.ts
> +  const removed = JSON.parse(list[index]);
`list[index]` não tem mais a execução que foi removida, porque o `Array.prototype.splice` já foi executado (linha 165). Como o retorno dessa função não é utilizado (até onde eu vi), dá pra remover isso aqui e o `return` da linha 175.

2020-05-23 22:01 UTC, rafaelruwer commented on src/services/timerFunction.ts
> +      currentState: execution.currentState,
Comentei também em `types.ts`: `currentState` é sempre `Finished`, acho que não precisa disso aqui.

2020-05-23 22:01 UTC, rafaelruwer commented on src/services/timerFunction.ts
> +  let arExecutions: OngoingExecution[] = JSON.parse(strArray);
Se tu trocar o `getOngoingExecutions` para retornar um array, você economiza esse parsing toda vez que for usar essa função.

2020-05-23 22:01 UTC, rafaelruwer commented on src/services/timerFunction.ts
> +  execution.currentState = ExecutionStatus.Paused;
Isso é um side effect relacionado a essa função? Vendo todos os lugares onde essa função é executada:
- `updateAll`, linha 156: invocada para todas as atividades `Initialized`, ou seja, todas serão pausadas (o que não é o objetivo da `updateAll`);
- `pauseExecution`, linha 91: lá, sim, tem sentido setar o estado para `Paused`;
- `finishExecution`, linha 121: o estado logo depois é setado para `Finished`, então atualizar o atributo aqui é desnecessário;

O mais grave está no que acontece no `updateAll`. Acho que vale a pena tirar essa atualização daqui e mover para o `pauseExecution` (nem precisa mudar o `finishExecution`).

2020-05-23 22:01 UTC, rafaelruwer commented on src/services/timerFunction.ts
> +const getSingleOngoingExecution = async (id: number) => {
Já fiz o mesmo comentário em algum lugar: vale mais mudar o `getOngoingExecutions` para retornar um array e "economizar" o `JSON.parse` daqui (e do outro lugar que invoca essa função).

2020-05-23 22:01 UTC, rafaelruwer commented on src/screens/EmptyScreen.tsx
> +    idPatient: 1234,
Vale tratar isso como `string`, porque, se não me engano, o usuário pode colocar letras no campo de prontuário.

2020-05-23 22:07 UTC, rafaelruwer requested changes

2020-05-23 22:07 UTC, rafaelruwer commented on src/services/types.ts
> +  idPatient: number;
Comentei isso na `EmptyScreen`: tem de ser `string`, porque o campo de prontuário permite letras.

2020-05-23 22:14 UTC, IgorBrehm commented on package.json
> +    "moment": "^2.26.0",
verdade, vou atualizar

2020-05-23 22:19 UTC, IgorBrehm commented on src/services/types.ts
> +  currentState: ExecutionStatus;
Bom ponto, é um erro de lógica

2020-05-24 00:18 UTC, MFischmann commented on src/services/timerFunction.ts
> +  execution.currentState = ExecutionStatus.Paused;
Erro surgiu quando adaptei código de dentro de pauseExecution para ser utilizado por múltiplas funções.

Corrigido commit 7c71348

2020-05-24 01:15 UTC, ghost submitted a review, later dismissed
Testes funcionais passaram todos, não foi mais possível reproduzir o erro de deleção de execução após as últimas mudanças e melhorias de código. Aprovando o MR...

2020-05-24 01:34 UTC, biancacamargomachado submitted a review, later dismissed

2020-05-24 03:26 UTC, rafaelruwer submitted a review, later dismissed

2020-05-24 03:36 UTC, rafaelruwer approved these changes

2020-05-24 03:37 UTC, merged